# Generated by Django 4.2.1 on 2023-05-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_ordermodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='quantity',
        ),
    ]
